name: CodSpeed 2024/3

on:
  push:
    branches:
      - main
    paths:
      - "2024/03/**"

jobs:
  codspeed:
    name: Run day 3 benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install pytest pytest-codspeed rpy2
      - uses: CodSpeedHQ/action@v3
        with:
          run: pytest 2024/03/ --codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
