name: CodSpeed 2024/2

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "2024/02/**"

jobs:
  codspeed:
    name: Run Day 2 Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Python dependencies
        run: pip install pytest pytest-codspeed
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::tidyverse, any::argparser
      - name: Run Codspeed Benchmark
        uses: CodSpeedHQ/action@v3
        with:
          run: pytest 2024/02/ --codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
