name: CodSpeed 2024/3

on:
  push:
    branches:
      - main
    paths:
      - "2024/03/**"
  workflow_dispatch:

jobs:
  codspeed:
    name: Run day 3 benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Python dependencies
        run: pip install pytest pytest-codspeed
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::tidyverse
      - uses: CodSpeedHQ/action@v3
        with:
          run: pytest 2024/03/ --codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
